yarnPath: .yarn/releases/yarn-3.1.1.cjs

# Hack for yarn dep resolution for react-scripts
packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
