import { all } from 'redux-saga/effects';
import {
  watchAutoLogin,
  watchGetGenres,
  watchGetCareers,
  watchGetLanguages,
  watchGetSubjects,
  watchGetTimezones,
  watchLogin,
  watchOnboardMentor,
  watchOnboardStudent,
  watchSubmitMentorSignUpForm,
  watchSubmitStudentRegistration,
  watchTaskStep,
  watchGetOpportunity,
  watchGetLibraryComputerSlots,
  watchGetUserPreferencesSlots,
  watchDeleteUserPreferencesSlotsSuccess,
  watchGetLibraryStudentPreferenceSlots,
  watchCreateUserPreferenceSlot,
  watchDeleteUserPreferenceSlot,
  watchGetUserDetail,
  watchVerifyMentorEmail,
  watchLogout
} from './actions';

export default function* rootSaga() {
  yield all([
    watchLogout(),
    watchVerifyMentorEmail(),
    watchGetUserDetail(),
    watchAutoLogin(),
    watchGetGenres(),
    watchGetLibraryComputerSlots(),
    watchCreateUserPreferenceSlot(),
    watchGetUserPreferencesSlots(),
    watchDeleteUserPreferenceSlot(),
    watchDeleteUserPreferencesSlotsSuccess(),
    watchGetLibraryStudentPreferenceSlots(),
    watchGetCareers(),
    watchGetLanguages(),
    watchGetSubjects(),
    watchGetTimezones(),
    watchLogin(),
    watchOnboardMentor(),
    watchOnboardStudent(),
    watchSubmitMentorSignUpForm(),
    watchSubmitStudentRegistration(),
    watchTaskStep(),
    watchGetOpportunity(),
  ]);
}
